//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TestMapDraw.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_ADD_SHAPEFILE               101
#define IDD_ADD_SQLITE                  102
#define IDC_SHAPE_PATH                  1000
#define IDC_BROWSE                      1001
#define IDC_ENABLE_ANNO                 1002
#define IDC_ANNO_FIELD                  1003
#define IDC_DB_PATH                     1004
#define IDC_TABLE                       1005
#define IDC_ANNO_SCALE                  1006
#define IDD_PAGE_SYMBOLOGY              103
#define IDD_PAGE_ANNOTATION             104
#define IDD_SYMBOL_EDITOR               105
#define IDD_PAGE_LABELS                 106
#define IDC_ENABLE_LABELS               1140
#define IDC_LABEL_FIELD                 1141
#define IDC_LABEL_SCALE                 1142
#define IDC_LABEL_FONT_SIZE             1143
#define IDC_LABEL_COLOR                 1144
#define IDC_LABEL_COLOR_BTN             1145
#define IDC_LABEL_HALO                  1146
#define IDC_LABEL_STRATEGY              1147
#define IDC_LABEL_PRIORITY              1148
#define IDC_LABEL_POINT_POS             1149
#define IDC_LABEL_OFFSET                1150
#define IDC_LABEL_LINE_ORIENT           1151
#define IDC_LABEL_LINE_POS              1152
#define IDC_LABEL_POLY_PLACEMENT        1153
#define IDC_LABEL_POLY_OUTSIDE          1154
#define IDC_LABEL_DUPLICATES            1155
#define IDC_LABEL_DUP_DISTANCE          1156
#define IDD_CONVERT_OSM                 107
#define IDD_OSM_PROGRESS                108
#define IDC_OSM_PATH                    1160
#define IDC_OSM_BROWSE                  1161
#define IDC_OSM_READ                    1162
#define IDC_OSM_INFO                    1163
#define IDC_OSM_DATASETS                1164
#define IDC_OSM_SELECT_ALL              1165
#define IDC_OSM_CLEAR_ALL               1166
#define IDC_OSM_OUTPUT                  1167
#define IDC_OSM_OUTPUT_BROWSE           1168
#define IDC_OSM_WEB_MERCATOR            1169
#define IDC_OSM_LANGUAGE                1170
#define IDC_OSM_NODE_CACHE              1171
#define IDC_OSM_ADD_TO_MAP              1172
#define IDC_PROGRESS_STAGE              1175
#define IDC_PROGRESS_BAR                1176
#define IDC_PROGRESS_COUNTS             1177
#define IDC_PROGRESS_TIME               1178
#define IDD_LAYER_PROPERTIES            109
#define IDD_PAGE_GENERAL                110
#define IDC_LAYER_NAME                  1180
#define IDC_LAYER_SOURCE                1181
#define IDC_LAYER_VISIBLE               1182
#define IDC_LAYER_SELECTABLE            1183
#define IDC_LAYER_MIN_SCALE             1184
#define IDC_LAYER_MAX_SCALE             1185
#define IDC_MIN_SCALE_CURRENT           1186
#define IDC_MAX_SCALE_CURRENT           1187
#define IDC_CURRENT_SCALE               1188
#define IDC_APPLY                       1189
#define IDC_LAYER_TREE                  1190
#define IDC_SYMBOLOGY_NOTE              1191
#define IDD_PAGE_DATA                   111
#define IDC_DATA_TABLE                  1192
#define IDC_DATA_WORKSPACE              1193
#define IDC_DATA_GEOMETRY               1194
#define IDC_DATA_EXTENT                 1195
#define IDC_DATA_SPATREF                1196
#define IDC_DATA_OID_FIELD              1197
#define IDC_DATA_SHAPE_FIELD            1198
#define IDC_DATA_FIELDS                 1199
#define IDD_MAP_PROPERTIES              112
#define IDC_MAP_NAME                    1200
#define IDC_MAP_CS_PRESET               1201
#define IDC_MAP_EPSG                    1202
#define IDC_MAP_EPSG_SET                1203
#define IDC_MAP_PROJ4                   1204
#define IDC_MAP_CS_INFO                 1205
#define IDC_MAP_UNITS                   1206
#define IDC_MAP_REF_SCALE_ON            1207
#define IDC_MAP_REF_SCALE               1208
#define IDC_MAP_REF_SCALE_CURRENT       1209
#define IDC_MAP_BG_COLOR                1210
#define IDC_MAP_BG_BTN                  1211
#define IDC_MAP_EXTENT                  1212
#define IDC_LAYER_SCALE_SYMBOLS         1213
#define IDC_LAYER_REF_SCALE_NOTE        1214
#define IDC_TABS                        1010
#define IDC_SELECTOR_TYPE               1011
#define IDC_SYMB_FIELD                  1012
#define IDC_ADD_VALUES                  1013
#define IDC_CLASSES                     1014
#define IDC_CLASSIFY                    1015
#define IDC_REMOVE_ITEM                 1016
#define IDC_DRAW_OTHER                  1017
#define IDC_ITEMS                       1018
#define IDC_SYM_GROUP                   1019
#define IDC_SYM_TYPE                    1020
#define IDC_CLASSES_LABEL               1021
#define IDC_SYMB_FIELD_LABEL            1022
#define IDC_PROP_LABEL0                 1100
#define IDC_PROP_LABEL1                 1101
#define IDC_PROP_LABEL2                 1102
#define IDC_PROP_LABEL3                 1103
#define IDC_PROP_LABEL4                 1104
#define IDC_PROP_LABEL5                 1105
#define IDC_PROP_LABEL6                 1106
#define IDC_PROP_LABEL7                 1107
#define IDC_PROP_EDIT0                  1110
#define IDC_PROP_EDIT1                  1111
#define IDC_PROP_EDIT2                  1112
#define IDC_PROP_EDIT3                  1113
#define IDC_PROP_EDIT4                  1114
#define IDC_PROP_EDIT5                  1115
#define IDC_PROP_EDIT6                  1116
#define IDC_PROP_EDIT7                  1117
#define IDC_PROP_COMBO0                 1120
#define IDC_PROP_COMBO1                 1121
#define IDC_PROP_COMBO2                 1122
#define IDC_PROP_COMBO3                 1123
#define IDC_PROP_COMBO4                 1124
#define IDC_PROP_COMBO5                 1125
#define IDC_PROP_COMBO6                 1126
#define IDC_PROP_COMBO7                 1127
#define IDC_PROP_BTN0                   1130
#define IDC_PROP_BTN1                   1131
#define IDC_PROP_BTN2                   1132
#define IDC_PROP_BTN3                   1133
#define IDC_PROP_BTN4                   1134
#define IDC_PROP_BTN5                   1135
#define IDC_PROP_BTN6                   1136
#define IDC_PROP_BTN7                   1137
#define IDR_MAINFRAME                   128
#define ID_REDRAW_MAP                   32775
#define ID_FULL_ZOOM                    32776
#define ID_ADD_SHAPE_FILE               32777
#define ID_REMOVE_ALL_LAYERS            32778
#define ID_ZOOM_IN                      32779
#define ID_ZOOM_OUT                     32780
#define ID_CLEAR_SELECTION              32781
#define ID_ADD_SQLITE_DB                32782
#define ID_CONVERT_SHAPE_TO_SQLITE      32783
#define ID_VIEW_3D                      32784
#define ID_TILT_UP                      32785
#define ID_TILT_DOWN                    32786
#define ID_ROTATE_LEFT                  32787
#define ID_ROTATE_RIGHT                 32788
#define ID_RESET_ROTATION               32789
#define ID_ADD_RASTER                   32790
#define ID_ZOOM_TO_LAYER                32791
#define ID_CONVERT_FROM_OSM             32792
#define ID_VIEW_LAYERS                  32793
#define ID_LAYER_PROPERTIES             32794
#define ID_LAYER_ZOOM                   32795
#define ID_LAYER_REMOVE                 32796
#define ID_NEW_GROUP_LAYER              32797
#define ID_MAP_PROPERTIES               32798

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1215
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
